### DISCUSSION TITLE
Install Matrix Home Server On Kubernetes - Vincze Janos Blog

### DISCUSSION THREAD

**Discussion by giscus** [jvincze84/jvincze84.github.io#5] [General]
# Install Matrix Home Server On Kubernetes - Vincze Janos Blog

https://readthedocs.vinczejanos.info/Blog/2021/10/27/Install_Matrix_Home_Server/

**Comment by m-emm** [comment]
Thanks a lot for this excellent tutorial! Maybe I didn't follow it closely enough, but in the end I lost some time. I want to help anybody who falls into the same trap. 
In short: Check the path of the log config file in the configmap for homeserver.yaml thoroughly, make sure it points to where the config map is mounted, namely `/config/xxxxx.log.config` and **not** `/data/xxxxx.log.config`!

Full story:
I lost time because I got the following error when starting the matrix pod:
```
PermissionError: [Errno 13] Permission denied: '/homeserver.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/synapse/app/homeserver.py", line 388, in <module>
    main()
  File "/usr/local/lib/python3.11/site-packages/synapse/app/homeserver.py", line 378, in main
    hs = setup(sys.argv[1:])
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synapse/app/homeserver.py", line 337, in setup
    synapse.config.logger.setup_logging(hs, config, use_worker_options=False)
  File "/usr/local/lib/python3.11/site-packages/synapse/config/logger.py", line 343, in setup_logging
    _setup_stdlib_logging(config, log_config_path, logBeginner=logBeginner)
  File "/usr/local/lib/python3.11/site-packages/synapse/config/logger.py", line 241, in _setup_stdlib_logging
    _load_logging_config(log_config_path)
  File "/usr/local/lib/python3.11/site-packages/synapse/config/logger.py", line 298, in _load_logging_config
    logging.config.dictConfig(log_config)
  File "/usr/local/lib/python3.11/logging/config.py", line 812, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/lib/python3.11/logging/config.py", line 569, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'
```
I googled quite a bit, and found these (misleading) issues:
https://github.com/matrix-org/synapse/issues/9970
https://github.com/A75G/docker-templates/issues/77

Everything in there didn't help, because the underlying problem was something else: Because in this tutorial, on kubernetes, we mount the configmap under /config, but in the first generated configfile, we had the log config under /data, so in the homeserver.yaml, it says:
```
log_config: "/data/example.com.log.config"
```

But when mounting the configfile under /config, we would have to change this to
```
log_config: "/config/example.com.log.config"
```

Beacause I didn't change that, synapse was unable to read the log config, but it didn't complain about this but just happily used a default configuration, where it uses a file hander to `/homeserver.log` , which is not writable by a non-root user. The symptom however looks exactly like the one of the two issues mentioned above. But the fixes mentioned there don't work, because you can change the logging config file in the configmap all you like, it is not found/read anyway. Ok, stupid mistake by me, but because you get no warning from synapse you can lose a lot of time with this.

I hope I can save some others some time. But still: This i an awesome tutorial!

**Reply by jvincze84** [reply]
Hi,
Thanks a lot for your comment.
Maybe I misunderstand something, but I'm failed to reproduce your problem.

First create the necessary dirs:
```bash
mkdir -p /tmp/matrix/config /tmp/matrix/data
```

After that generate the config:
```bash
docker run -it --rm \
    --mount type=bind,src=/tmp/matrix/config,dst=/config \
    --mount type=bind,src=/tmp/matrix/data,dst=/data \
    -e SYNAPSE_SERVER_NAME=matrix-kub-test.duckdns.org \
    -e SYNAPSE_REPORT_STATS=yes \
    -e SYNAPSE_CONFIG_DIR=/config \
    -e SYNAPSE_CONFIG_PATH=/config/homeserver.yaml \
    matrixdotorg/synapse:latest generate
```

**Output:**

```plain
root@nuc:/tmp# docker run -it --rm \
    --mount type=bind,src=/tmp/matrix/config,dst=/config \
    --mount type=bind,src=/tmp/matrix/data,dst=/data \
    -e SYNAPSE_SERVER_NAME=matrix-kub-test.duckdns.org \
    -e SYNAPSE_REPORT_STATS=yes \
    -e SYNAPSE_CONFIG_DIR=/config \
    -e SYNAPSE_CONFIG_PATH=/config/homeserver.yaml \
    matrixdotorg/synapse:latest generate
Setting ownership on /data to 991:991
Creating log config /config/matrix-kub-test.duckdns.org.log.config
Generating config file /config/homeserver.yaml
Generating signing key file /config/matrix-kub-test.duckdns.org.signing.key
A config file has been generated in '/config/homeserver.yaml' for server name 'matrix-kub-test.duckdns.org'. Please review this file and customise it to your needs.
```

Check `log_config`:

```bash
root@nuc:/tmp/matrix/config# cat homeserver.yaml | grep -C 5 log
        compress: false
database:
  name: sqlite3
  args:
    database: /data/homeserver.db
log_config: "/config/matrix-kub-test.duckdns.org.log.config"
media_store_path: /data/media_store
registration_shared_secret: "x-WEtGil5GB7k;1voH~,7aypDs.kwobaR3AJ23.Id.gHpPlBK3"
report_stats: true
macaroon_secret_key: "5-XKK7F5S^EudTx~now=Ck&RejkqF#rnqLr2o^CWHr+GNJfr6t"
form_secret: "k=QygnVGvCl74Mqthe;ub#Dtd-Xy4dU-hTPx81@JW@L6DcT1b;"
```

Can you double check the following ENVs:

* SYNAPSE_CONFIG_DIR
* SYNAPSE_CONFIG_PATH

Thanks,
JVincze

**Reply by jvincze84** [reply]
It seems the Synapse changed the config generation process, now it is also necessary to specify the data folder:

```bash
mkdir -p /tmp/matrix/data
```

And mount it:
```bash
--mount type=bind,src=/tmp/matrix/data,dst=/data \
```

I'm going to fix this.

**Comment by jattind** [comment]
Thanks a lot for a really useful article. I am trying to follow the kubernetes section, but hit a similar issue to above. I am getting slightly different permission error. I wonder if we have to also create a media_store dir under data and mount it?
```
Starting synapse with args -m synapse.app.homeserver --config-path /config/homeserver.yaml
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/synapse/app/homeserver.py", line 398, in <module>
    main()
  File "/usr/local/lib/python3.11/site-packages/synapse/app/homeserver.py", line 388, in main
    hs = setup(sys.argv[1:])
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synapse/app/homeserver.py", line 297, in setup
    config = HomeServerConfig.load_or_generate_config(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synapse/config/_base.py", line 801, in load_or_generate_config
    obj.parse_config_dict(
  File "/usr/local/lib/python3.11/site-packages/synapse/config/_base.py", line 822, in parse_config_dict
    self.invoke_all(
  File "/usr/local/lib/python3.11/site-packages/synapse/config/_base.py", line 421, in invoke_all
    res[config_class.section] = getattr(config, func_name)(*args, **kwargs)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synapse/config/repository.py", line 140, in read_config
    self.media_store_path = self.ensure_directory(
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synapse/config/_base.py", line 270, in ensure_directory
    os.makedirs(dir_path, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/data/media_store'
```

**Reply by jattind** [reply]
If I change the media_store patch in ConfigMap to /data, it pod seems to get further, but gets an error on DB:
Starting synapse with args -m synapse.app.homeserver --config-path /config/homeserver.yaml
This server is configured to use 'matrix.org' as its trusted key server via the
'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
server since it is long-lived, stable and trusted. However, some admins may
wish to use another server for this purpose.

To suppress this warning and continue using 'matrix.org', admins should set
'suppress_key_server_warning' to 'true' in homeserver.yaml.
--------------------------------------------------------------------------------
2023-04-27 22:28:12,167 - root - 350 - WARNING - main - ***** STARTING SERVER *****
2023-04-27 22:28:12,167 - root - 351 - WARNING - main - Server /usr/local/lib/python3.11/site-packages/synapse/app/homeserver.py version 1.82.0
2023-04-27 22:28:12,167 - root - 356 - INFO - main - Server hostname: matrix20002.senode.dev
2023-04-27 22:28:12,167 - root - 357 - INFO - main - Instance name: master
2023-04-27 22:28:12,167 - root - 358 - INFO - main - Twisted reactor: EPollReactor
2023-04-27 22:28:12,167 - synapse.app.homeserver - 349 - INFO - main - Setting up server
2023-04-27 22:28:12,168 - synapse.server - 327 - INFO - main - Setting up.
2023-04-27 22:28:12,168 - synapse.app._base - 212 - ERROR - main - Exception during startup
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/synapse/app/homeserver.py", line 352, in setup
    hs.setup()
  File "/usr/local/lib/python3.11/site-packages/synapse/server.py", line 329, in setup
    self.datastores = Databases(self.DATASTORE_CLASS, self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/__init__.py", line 65, in __init__
    with make_conn(database_config, engine, "startup") as db_conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 161, in make_conn
    native_db_conn = engine.module.connect(**db_params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
********************************************
 Error during initialisation:
    unable to open database file
 There may be more information in the logs.
********************************************

**Comment by jvincze84** [comment]
Hi,
Thanks for your comment.  I have just tested the maifest, and I get same error message:
```
PermissionError: [Errno 13] Permission denied: '/data/media_store'
```

This is because the matrix container runs 991 UID and GUID by default. Depending on your persistnet volume provider, I think the mounpath is not r/w for this UID.
I made some research, and found that, the matrix container entrypoint `/start.py` do the followings:

```python
    # if we were given an explicit user to switch to, do so
    ownership = None
    if "UID" in environ:
        desired_uid = int(environ["UID"])
        desired_gid = int(environ.get("GID", "991"))
        ownership = f"{desired_uid}:{desired_gid}"
    elif os.getuid() == 0:
        # otherwise, if we are running as root, use user 991
        ownership = "991:991"
....
...
...
    if ownership is not None:
        args = ["gosu", ownership] + args
        flush_buffers()
        os.execve("/usr/sbin/gosu", args, environ)
    else:
        flush_buffers()
        os.execve(sys.executable, args, environ)
```

Without knowing your system, I can suggest a really easy fix for your problem. :)

Modify the `Deployment-matrix.yaml`, and add `fsGroup: 991` securityContext:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: matrix
  name: matrix
  namespace: matrix
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: matrix
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: matrix
      name: matrix
    spec:
      containers:
      - env:
        - name: SYNAPSE_CONFIG_DIR
          value: /config
        - name: SYNAPSE_CONFIG_PATH
          value: /config/homeserver.yaml
        image: matrixdotorg/synapse:latest
        imagePullPolicy: Always
        name: matrix
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config/homeserver.yaml
          name: matrix-cm
          subPath: homeserver.yaml
        - mountPath: /config/matrix-kub-test.duckdns.org.log.config
          name: matrix-cm
          subPath: matrix-kub-test.duckdns.org.log.config
        - mountPath: /data
          name: matrix-pv
          subPath: matrix
        - mountPath: /config/matrix-kub-test.duckdns.org.signing.key
          name: matrix-key
          subPath: matrix-kub-test.duckdns.org.signing.key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 991
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 10
      volumes:
      - name: matrix-key
        secret:
          defaultMode: 420
          items:
          - key: matrix-kub-test.duckdns.org.signing.key
            path: matrix-kub-test.duckdns.org.signing.key
          secretName: matrix-key
      - name: matrix-pv
        persistentVolumeClaim:
          claimName: matrix-storage
      - name: matrix-cm
        configMap:
          name: matrix
          defaultMode: 420
          items:
          - key: homeserver.yaml
            path: homeserver.yaml
          - key: matrix-kub-test.duckdns.org.log.config
            path: matrix-kub-test.duckdns.org.log.config
```
